name: GHCR Test
on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build test image
        run: |
          echo -e "FROM alpine:latest\nCMD echo Hello GHCR" > Dockerfile
          docker build -t ghcr.io/${{ github.actor }}/test:1.0 .
      - name: Push test image
        run: docker push ghcr.io/${{ github.actor }}/test:1.0
